### PR TITLE
Replace AvalonEdit with Monaco for inputs and outputs

### PR DESCRIPTION
**Pull request by highstreeto**
This replaces AvalonEdit in the input and output tabs, which enables better syntax highlighting as discussed in #7.

Open tasks:
- [x] Detect if WebView2 is available and switch back to AvalonEdit, if no WebView2 runtime is not installed
- [x] Handle worWarp, textSize and lineNumber changes (currently ignored)

### CODE REVIEW

**Comment by NeilMacMullen** [comment]
wow - this super nice - THANK YOU ! 

wrt..

 > Detect if WebView2 is available and switch back to AvalonEdit, if no WebView2 runtime is not installed
I'd be fine with making WebView a mandatory prerequisite and just chucking up  a warning dialog before shutting down the application.  Or just fix in the documentation with big warning in the readme.


> Handle wordWarp, textSize and lineNumber changes (currently ignored)

Yes - would definitely be nice to get back (especially as they are now persisted in application settings) but I think the improved syntax highlighting is a stronger feature that any of these so would be happy to merge this and lose those for a while.

**Comment by NeilMacMullen** [comment]
Oh - would be good to add a line or two to doc\buildFromSource.md to explain the extra step of installing the WebVIew SDK if you are still making changes.  Otherwise I can do it post-merge.

**Comment by highstreeto** [comment]
> Oh - would be good to add a line or two to doc\buildFromSource.md to explain the extra step of installing the WebVIew SDK if you are still making changes. Otherwise I can do it post-merge.

For the build itself no installed SDK should be needed (should all be in the NuGet package).

**Comment by NeilMacMullen** [comment]
>For the build itself no installed SDK should be needed (should all be in the NuGet package).

Oh, nice !

**Comment by highstreeto** [comment]
> I'd be fine with making WebView a mandatory prerequisite and just chucking up a warning dialog before shutting down the application. Or just fix in the documentation with big warning in the readme. Definitely no need to fallback to AvalonEdit.

I added a check at startup, and if no WebView2 runtime is detected an error is shown and the app is terminated.

**Comment by highstreeto** [comment]
> Yes - would definitely be nice to get back (especially as they are now persisted in application settings) but I think the improved syntax highlighting is a stronger feature that any of these so would be happy to merge this and lose those for a while.

Ok, leaving that for later

**Comment by NeilMacMullen** [comment]
super :-)  Merging....

**Pull request merged**
